-- 添加 design_groups 表缺失的字段
ALTER TABLE design_groups
ADD COLUMN IF NOT EXISTS width DECIMAL(10, 2) COMMENT '宽度(mm)',
ADD COLUMN IF NOT EXISTS height DECIMAL(10, 2) COMMENT '高度(mm)',
ADD COLUMN IF NOT EXISTS area DECIMAL(10, 4) COMMENT '面积(平方米)',
ADD COLUMN IF NOT EXISTS material VARCHAR(100) COMMENT '材质',
ADD COLUMN IF NOT EXISTS remark TEXT COMMENT '备注';
